services:
  - type: background
    name: linkedin-bot-worker
    env: docker
    plan: starter
    dockerfilePath: ./deployments/render/worker/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: linkedin-bot-redis
          property: connectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE
        sync: false
      - key: LINKEDIN_COOKIES_JSON
        sync: false
      - key: PROXY_URL
        sync: false
      - key: QUEUE_NAME
        value: linkedin-jobs
      - key: BULLMQ_PREFIX
        value: bull
      - key: WORKER_CONCURRENCY
        value: 1
      - key: LOG_LEVEL
        value: info
      # Resource management
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1024 --optimize-for-size"
      # Graceful shutdown configuration
      - key: SIGTERM_TIMEOUT
        value: 60000
      # Chrome/Puppeteer configuration
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: CHROME_USER_DATA_DIR
        value: /tmp/chrome-user-data
    
  - type: redis
    name: linkedin-bot-redis
    plan: starter
    maxmemoryPolicy: noeviction